trigger:
  paths:
    include:
      - documentation/*

variables:
- group: test-tf
  # serviceconnection
- group: DevOps-Org-Defaults
  # DevOps-Domain
  # DevOps-Organization
  # DevOps-Project
  # DevOps-MainBranch
- group: Publish-Documentation-Credentials
  # PullRequest-Documentation-Email
  # PullRequest-Documentation-PAT

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: mgmt_pullrequest_template
    type: git
    name: "Cloudeon CCoE/mgmt-pullrequest-template"
    ref: refs/tags/1.4.0

jobs:
- template: /templates/pullrequest.job.yml@mgmt_pullrequest_template
  parameters:
    devOpsDomain: $(DevOpsDomain)
    devOpsOrganization: $(DevOpsOrganization)
    devOpsProject: $(DevOpsProject)
    serviceConnection: $(serviceconnection)
    userEmail: $(PullRequest-Documentation-Email)
    userPat: $(PullRequest-Documentation-PAT)